# Generated by Django 5.2.3 on 2025-08-18 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0002_projectjoinrequest_projectmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmessage',
            options={},
        ),
        migrations.AddField(
            model_name='projectmessage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='collab.project'),
        ),
        migrations.AlterField(
            model_name='projectmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projectmessage',
            name='join_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='collab.projectjoinrequest'),
        ),
    ]
